<?php
return array(
	'location_head_low'					=> 'ปาก',
	'location_right_hand'				=> 'มือขวา (อาวุธ)',
	'location_garment'					=> 'มัพ',
	'location_right_accessory'			=> 'ประดับ (ข้างขวา)',
	'location_armor'					=> 'เสื้อ',
	'location_left_hand'				=> 'มือซ้าย (โล่)',
	'location_shoes'					=> 'รองเท้า',
	'location_left_accessory'			=> 'ประดับ (ข้างซ้าย)',
	'location_head_top'					=> 'หัว',
	'location_head_mid'					=> 'หู',
	'location_costume_head_top'			=> 'คอสตูมหัว',
	'location_costume_head_mid'			=> 'คอสตูมหู',
	'location_costume_head_low'			=> 'คอสตูมปาก',
	'location_costume_garment'			=> 'คอสตูมมัพ',
	'location_ammo'						=> 'ลูกธนู/กระสุน',
	'location_shadow_armor'				=> 'คอสตูมเสื้อ',
	'location_shadow_weapon'			=> 'คอสตูมอาวุธ',
	'location_shadow_shield'			=> 'คอสตูมโล่',
	'location_shadow_shoes'				=> 'คอสตูมรองเท้า',
	'location_shadow_right_accessory'	=> 'คอสตูมประดับ (ข้างขวา)',
	'location_shadow_left_accessory'	=> 'คอสตูมประดับ (ข้างซ้าย)',
)
?>
