<?php
return array(
	'mode_aggressive'			=> 'โจมตีผู้เล่นก่อน',
	'mode_angry'				=> 'โกรธ',
	'mode_assist'				=> 'ช่วยเหลือมอนสเตอร์กันเอง',
	'mode_canattack'			=> 'สามารถโจมตีได้',
	'mode_canmove'				=> 'สามารถเดินได้',
	'mode_castsensorchase'		=> 'Cast Sensor Chase',
	'mode_castsensoridle'		=> 'Cast Sensor Idle',
	'mode_changechase'			=> 'เปลี่ยนเป้าหมายไล่ล่า',
	'mode_changetargetchase'	=> 'เปลี่ยนเป้าหมายโจมตี',
	'mode_changetargetmelee'	=> 'เปลี่ยนเป้าหมายระยะใกล้',
	'mode_detector'				=> 'ตรวจจับเวทย์ที่ร่ายใส่',
	'mode_fixeditemdrop'		=> 'Fixed Item Drop',
	'mode_ignoremagic'			=> 'ไม่โจมตีผู้เล่นร่ายเวทย์', 
	'mode_ignoremelee'			=> 'ไม่โจมตีผู้เล่นตีใกล้',
	'mode_ignoremisc'			=> 'ไม่โจมตีผู้เล่นอื่นๆ',
	'mode_ignoreranged'			=> 'ไม่โจมตีผู้เล่นตีระยะไกล',
	'mode_knockbackimmune'		=> 'ไม่กระเด็น',
	'mode_looter'				=> 'สามารถเก็บของได้',
	'mode_mvp'					=> 'MVP',
	'mode_norandomwalk'			=> 'พืช',
	'mode_randomtarget'			=> 'Random Target',
	'mode_skillimmune'			=> 'ป้องกันสกิล',
	'mode_statusimmune'			=> 'ป้องกันสถานะ',
	'mode_targetweak'			=> 'โจมตีผู้เล่นก่อน',
	'mode_teleportblock'		=> 'Teleport Block',
)
?>
